services:
  db:
    image: postgres:17
    container_name: booklypro_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: booklypro
      POSTGRES_USER: booklypro_user
      POSTGRES_PASSWORD: booklypro_password
    ports:
      - "5433:5432"
    volumes:
      - booklypro_postgres_data:/var/lib/postgresql/data

volumes:
  booklypro_postgres_data: